
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  testsshfs:
    if: ${{ !contains(github.repository, 'solaris') && !contains(github.repository, 'dragonflybsd')}}
    strategy:
      matrix:
        release: [ {{ALL_RELEASES}}, ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: sshfs {{VM_NAME}}
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in {{VM_NAME}}
      id: test
      uses: {{GITHUB_REPOSITORY}}@{{GITHUB_RUN_ID}}
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          {{VM_PREPARE}}
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        sync: sshfs
        run: |
          tree .
          tree $HOME/work/
    - name: Test NAT
      run: 
        ssh -p 10022 root@localhost "uname -a;whoami;pwd"

  test:
    strategy:
      matrix:
        release: [ {{ALL_RELEASES}}, ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: {{VM_NAME}}
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in {{VM_NAME}}
      id: test
      uses: {{GITHUB_REPOSITORY}}@{{GITHUB_RUN_ID}}
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          {{VM_PREPARE}}
        mem: 2048
        copyback: false
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
{{VM_RUN}}
    - name: Test NAT
      run: 
        ssh -p 10022 root@localhost "uname -a;whoami;pwd"










